### ISSUE TITLE
Unambiguous environment variables

### ISSUE THREAD

**Issue by lfportal** [shirren/bifrost#1]
The environment variables `NAMESPACE`, `KEY_NAME` and `KEY_SECRET` are quite ambiguous. Other azure services might require the use of a namespace in a project. Can we rename these variables to something more precise? Maybe `AZURE_SERVICE_BUS_NAMESPACE`, `AZURE_KEY_NAME` and `AZURE_KEY_SECRET`?

**Comment by shirren** [comment]
@lfportal I agree that NAMESPACE, KEY_NAME, and KEY_SECRET are ambigious, but I think saying AZURE is redundant, as the Bifrost will only work with Azure for the foreseeable future. So perhaps BUS_NAMESPACE, BUS_KEY_NAME & BUS_KEY_SECRET?

**Comment by shirren** [comment]
@lfportal agreed, but a better set of names would be AZURE_BUS_NAMESPACE, AZURE_BUS_KEY_NAME & AZURE_BUS_KEY_SECRET
