### ISSUE TITLE
Simpler interface for receiving messages

### ISSUE THREAD

**Issue by lfportal** [shirren/bifrost#10]
If a client chooses to ignore the header and only look at the message body, they must always call `.body` to retrieve the body. To simplify usage we can change the interface to something like `.receive_message(body, header)` for the 1.0 release.

**Comment by shirren** [comment]
@lfportal this would be a breaking change. I am happy to make this change if it simplifies the client interface. Please go ahead and make the change, please ensure all the specs still pass.
