### ISSUE TITLE
Expose message id to workers

### ISSUE THREAD

**Issue by lfportal** [shirren/bifrost#8]
I would like access to the `message_id` from a worker to use as a message receipt. I think this could be useful to have for auditing. Can we pass the `message_id` into the Proc call? i.e. `proc { |m, message_id| puts m }`. This should remain backwards compatible.

**Comment by shirren** [comment]
@lfportal the approach we have taken is to pass the Bifrost message into the worker instead of the BrokeredMessage payload. This means now you can say m.message_id or m.resource_id to grab the identifier of the message or resource (which are the same really) and to grab the payload message.body
